name: Changelog test

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check changelog format
      run: |
        ./scripts/check-changelog.sh

